spring:
  profiles:
    active: dev
  application:
    name: oauth2-server

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true