server:
  port: 8081

security:
  oauth2:
    authorization:
      check-token-access: http://localhost:8082/oauth/check_token
    resource:
      id: order-service
      user-info-uri: http://localhost:8082/user
      token-info-uri: http://localhost:8082/oauth/check_token
      prefer-token-info: false