server:
  port: 8081

spring:
  application:
    name: user-service
  profile:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:uhms
    schema: classpath:schema.sql
    data: classpath:data.sql
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    static-location: classpath:/static/
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true

mybatis:
  type-aliases-package: org.uhms.user.models
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true


#security:
#  oauth2:
#    authorization:
#      check-token-access: http://localhost:8082/oauth/check_token
#    resource:
#      id: order-service
#      user-info-uri: http://localhost:8082/user
#      token-info-uri: http://localhost:8082/oauth/check_token
#      prefer-token-info: false