server:
  port: 8090
  error:
    path: /error
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true
spring:
  application:
    name: zuul-getway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


zuul:
  routes:
    users:
      path: /user/**
      serviceId: user-service